---
- name: Enforce s3 bucket versioning on aws
  hosts: localhost
  gather_facts: false
  tasks:
   - name: List all the s3 buckets
     amazon.aws.s3_bucket_info:
     register: result
    
   - debug: 
       var: result
   
   - name: Enable versioning on the buckets
     amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: true
     loop: "{{ result.buckets }}" 
