---
- hosts: all
  become: true
  
  tasks:
   - name: Make sure the packages openssh and openssl are upto date
     ansible.builtin.apt:
       name: "{{ item }}"
       state: latest
     ignore_errors: yes
     loop:
         - openssh
         - openssl
   - name: verify if Docker is installed
     ansible.builtin.command: docker --version
     register: output
     ignore_errors: yes
   - ansible.builtin.debug:
        var: output
   - name: Install Docker
     ansible.builtin.apt:
       name: docker.io
       state: present 
#     when: output.failed
   - name: wait for 100 seconds
     ansible.builtin.pause:
       seconds: 100
   - name: Uninstall docker
     ansible.builtin.apt:
       name: docker.io
       state: absent
